# Generated by Django 2.1 on 2018-09-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('team_name', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=3)),
            ],
        ),
    ]
