# Generated by Django 2.1.3 on 2018-11-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_teamphoto_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamphoto',
            name='Image',
            field=models.ImageField(upload_to=''),
        ),
    ]
