# Generated by Django 2.1.3 on 2019-11-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181110_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbassadorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('team_email', models.EmailField(max_length=200)),
                ('message', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
